# Generated by Django 3.1.5 on 2021-02-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bb',
            old_name='prise',
            new_name='price',
        ),
    ]
