# Generated by Django 3.1.5 on 2021-02-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20210203_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['rubric_name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='rubric',
            old_name='name',
            new_name='rubric_name',
        ),
    ]
